### PR TITLE
working version of darcy static

### PR DESCRIPTION
**Pull request by ssafaei**

### CODE REVIEW

**Review by hsorby — CHANGES_REQUESTED** [review]
Documentation needs to be updated to match implementation.

**Review by hsorby — CHANGES_REQUESTED** [review]
Remove *output* directory.

README.rst is not appropriate for this repository.

**Comment by ssafaei** [comment]
This one is good to go for testing.

**Review by hsorby — COMMENTED** [review]
What absolute tolerance are you expecting for this example I'm seeing errors of:

```
669c669
<   9.9999999999995937E-01
--- field 1	absolute error 5.75e-14
>   1.0000000000000169E+00
```

which is well above 5\*epsilon.

**Pull request merged**
